name: build-gnucobol-3.1.2-windows-mingw.yml

on:
  workflow_dispatch
  
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
    MSYS2_INSTALL_ROOT: d:\
    ARTIFACT_NAME: gnucobol-3.1.2-windows-mingw
  
permissions:
  contents: read

jobs:
  gnucobol_3_1_2_windows_x64_mingw:
    name: gnucobol_3_1_2_windows_x64_mingw
    runs-on: windows-latest  
    env:
      PKG_NAME: gnucobol-3.1.2-windows-x64-mingw
      MSYS2_SYSTEM: MINGW64
      PLATFORM_ID: x86_64
      
    steps:
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
         location: ${{ env.MSYS2_INSTALL_ROOT }}
         msystem: ${{ env.MSYS2_SYSTEM }}

    - name: Installing GnuCOBOL
      shell: msys2 {0}
      env:
         PKG_DIR: $(cygpath '${{ github.workspace }}')/gnucobol-3.1.2-windows-mingw-${{ env.PLATFORM_ID }}
         PKG_NAME: gnucobol-3.1.2-windows-mingw-${{ env.PLATFORM_ID }}
      run: |
        uname -a
        mkdir -p ${{ env.PKG_DIR }}
        pacman --noconfirm --root=${{ env.PKG_DIR }} --dbpath=${{ env.PKG_DIR }} -Sy mingw-w64-x86_64-gnucobol mingw-w64-x86_64-gnucobol
 
    - name: Build package
      shell: cmd
      run: |
         7z a -r -w${{ github.workspace }} ${{ env.PKG_NAME }}.7z ${{ env.PKG_NAME }}
         
    - name: Archive package
      uses: actions/upload-artifact@v3  
      with:
         name: ${{ env.ARTIFACT_NAME }}
         path: ${{ github.workspace }}/${{ env.PKG_NAME }}.7z

  gnucobol_3_1_2_windows_x86_mingw:
    name: gnucobol_3_1_2_windows_x86_mingw
    runs-on: windows-latest  
    env:
      PKG_NAME: gnucobol-3.1.2-windows-x86-mingw
      MSYS2_SYSTEM: MINGW32
      PLATFORM_ID: i686

    steps:
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
         location: ${{ env.MSYS2_INSTALL_ROOT }}
         msystem: ${{ env.MSYS2_SYSTEM }}

    - name: Installing GnuCOBOL
      shell: msys2 {0}
      env:
         PKG_DIR: $(cygpath '${{ github.workspace }}')/gnucobol-3.1.2-windows-mingw-${{ env.PLATFORM_ID }}
         PKG_NAME: gnucobol-3.1.2-windows-mingw-${{ env.PLATFORM_ID }}
      run: |
        uname -a
        mkdir -p ${{ env.PKG_DIR }}
        pacman --noconfirm --root=${{ env.PKG_DIR }} --dbpath=${{ env.PKG_DIR }} -Sy mingw-w64-x86_64-gnucobol mingw-w64-x86_64-gnucobol
 
    - name: Build package
      shell: cmd
      run: |
         7z a -r -w${{ github.workspace }} ${{ env.PKG_NAME }}.7z ${{ env.PKG_NAME }}
         
    - name: Archive package
      uses: actions/upload-artifact@v3  
      with:
         name: ${{ env.ARTIFACT_NAME }}
         path: ${{ github.workspace }}/${{ env.PKG_NAME }}.7z
