name: build-gnucobol-3.1.2-windows-x64-mingw.yml

on:
  workflow_dispatch
  
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
    WORKSPACE: ${{ github.workspace }}
    MSYS2_INSTALL_ROOT: d:\
  
permissions:
  contents: read

jobs:
  gnucobol_3_1_2_windows_x64_mingw:
    env:
      PKG_NAME: gnucobol-3.1.2-windows-x64-mingw
      MSYS2_SYSTEM: MINGW64
      PLATFORM_ID: x86_64
      PLATFORM_SHORT_ID: x64    
      
    name: Install gnucobol-3.1.2-windows-x64-mingw
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
         location: ${{ env.MSYS2_INSTALL_ROOT }}
         msystem: ${{ env.MSYS2_SYSTEM }}
         install: mingw-w64-${{ env.PLATFORM_ID }}-gnucobol    
         
    - name: Build package
      shell: cmd
      env:
          PKGDIR: ${{ github.workspace }}\${{ env.PKG_NAME }}
          MSYS2_INSTALL_DIR: ${{ env.MSYS2_INSTALL_ROOT }}\msys64
      run: |
         echo Package directory: %PKGDIR%
         echo Copying: %MSYS2_INSTALL_DIR% => %PKGDIR%
         robocopy /E /NFL /NDL /nc /ns /np %MSYS2_INSTALL_DIR%  %PKGDIR%

    - name: Archive package
      uses: actions/upload-artifact@v3  
      with:
         name: ${{ env.PKG_NAME }}
         path: ${{ github.workspace }}/${{ env.PKG_NAME }}/
