name: build-gnucobol-3.1.2-windows-x64-mingw.yml

on:
  workflow_dispatch
  
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  PLATFORM_ID: x86_64
  
permissions:
  contents: read

jobs:
  gnucobol_3_1_2_windows_x64_mingw:
    name: gnucobol-3.1.2-windows-x64-mingw
    env:   
      PLATFORM_ID: x64    
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
         msystem: ${{matrix.sys}}
         install: mingw-w64-${{ env.PLATFORM_ID }}-gnucobol    
    - shell: msys2 {0}
      run: |
         uname -a
         cobc -info
#
#    - name: Build
#      shell: cmd
#      working-directory: ${{ github.workspace }}
#      env:
#          QTDIR: ${{env.Qt5_Dir}}
#          QtMsBuild: ${{ github.workspace }}\QtMsBuild
#          QtToolsPath: ${{env.Qt5_Dir}}\bin
#          LIBPATH: ${{env.Qt5_Dir}}\lib
#      run: |
#        echo "VCPKG_ROOT         : ${{env.VCPKG_ROOT}}"
#        echo "BUILD_PLATFORM     : ${{env.BUILD_PLATFORM}}"
#        echo "BUILD_CONFIGURATION: ${{env.BUILD_CONFIGURATION}}"
#        echo "SOLUTION_FILE_PATH : ${{env.SOLUTION_FILE_PATH}}"
#        echo #define VERSION "${{ env.GIX_SQL_VERSION }}" > gixsql/config.h
#        7z x -y ${{ github.workspace }}\build-tools\QtMsBuild.zip     
#        copy /Y ${{ github.workspace }}\libs\libdwarf\config.h.msvc ${{ github.workspace }}\libs\libdwarf\config.h
#        copy /Y gix-ide\GixVersion.h.tpl gix-ide\GixVersion.h
#        sed -i 's/{GIXIDEMAJ}/${{env.GIX_VER_GIXIDEMAJ}}/' gix-ide\GixVersion.h
#        sed -i 's/{GIXIDEMIN}/${{env.GIX_VER_GIXIDEMIN}}/' gix-ide\GixVersion.h
#        sed -i 's/{GIXIDEREL}/${{env.GIX_VER_GIXIDEREL}}/' gix-ide\GixVersion.h
#        sed -i 's/{GIXIDEBLD}/${{env.GIX_VER_GIXIDEBLD}}/' gix-ide\GixVersion.h
#        vcpkg integrate install
#        msbuild /m /p:Platform=${{env.BUILD_PLATFORM}} /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:IncludePath="${{env.Qt5_Dir}}/include;${{env.Qt5_Dir}}/include/QtCore;${{env.Qt5_Dir}}/include/QtWidgets;${{env.Qt5_Dir}}/include/QtXml;${{env.Qt5_Dir}}/include/QtXmlPatterns;${{env.Qt5_Dir}}/include/QtNetwork;${{env.Qt5_Dir}}/include/QtUiTools;${{env.Qt5_Dir}}/include/QtGui;${{ '$(IncludePath)' }}" /p:LibPath="${{env.Qt5_Dir}}/lib;${{ '$(LibPath)' }}"
#
#    - name: Archive production artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: archive-gix-ide-windows-msvc-${{env.PLATFORM_ID}}-artifacts
#        path: |
#          ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/*.dll
#          ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/libgixsql.lib
#          ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/*.exe
#          
